### PR TITLE
Add reminders class, added test cases for unit testing and integration testing 

### PR DESCRIPTION
**Pull request by minpyaemoe**
user can now add reminders to storage

### CODE REVIEW

**Review by Nanosync — APPROVED** [review]

**Comment by Nanosync** [comment]
#34

**Comment by Nanosync** [comment]
Coverage dropped https://coveralls.io/builds/26420725

**Comment by minpyaemoe** [comment]
Okay, i will add more test cases

**Comment by minpyaemoe** [comment]
image

Increased code coverage!

**Pull request merged**
