### PR TITLE
Updated UI

### PR DESCRIPTION
**Pull request by jonathantjendana**
image
image

MoneyGoWhere is now responsive :)

#193, #206 , #177

### CODE REVIEW

**Comment by minpyaemoe** [comment]
Does the reminder list also still responsive after this change? I don't have your code so i cant test it out

**Comment by Nanosync** [comment]
Could we add this as well so that the budget area is clearer? (Highlighted in image)

image

Great work btw!

**Review by Nanosync — APPROVED** [review]
Can be merged, suggestion included in previous comment

**Comment by jonathantjendana** [comment]
> Does the reminder list also still responsive after this change? I don't have your code so i cant test it out

you can pull from my branch if you want to test it out. However, it is responsive in which it shows a horizontal sliding bar when the size is resized to a smaller size. Same as the spending list

**Comment by jonathantjendana** [comment]
> Could we add this as well so that the budget area is clearer? (Highlighted in image)
> 
> image

this suggestion should be assigned to @austinsantoso

**Comment by Nanosync** [comment]
Fixes #206

**Pull request merged**
